### PR TITLE
Wrap JSON parse in try catch

### PR DESCRIPTION
**Pull request by lemonJS**
Prevents errors when the Google response contains malformed JSON.

### CODE REVIEW

**Comment by bradvogel** [comment]
What google api response returns corrupted json?

**Comment by lemonJS** [comment]
```
{
  "message": "Unexpected token N in JSON at position 0",
  "name": "SyntaxError",
  "stack": "SyntaxError: Unexpected token N in JSON at position 0\n at JSON.parse (<anonymous>)\n at PartStream.<anonymous> (/src/node_modules/batchelor/lib/batchelor.js:223:33)\n at emitNone (events.js:91:20)\n at PartStream.emit (events.js:186:7)\n at endReadableNT (_stream_readable.js:974:12)\n at _combinedTickCallback (internal/process/next_tick.js:74:11)\n at process._tickDomainCallback (internal/process/next_tick.js:122:9)"
}
```

It appears that if we try to label an email that has been deleted (someone deletes an email when it first comes in) then the response from Google isn't valid JSON.

**Comment by bradvogel** [comment]
Can you share the exact error that gmail returns?

**Comment by lemonJS** [comment]
@bradvogel Sure, here you go:
```
REST request returned 405; body: {\"error\":{\"code\":\"ErrorInvalidRequest\",\"message\":\"The OData request is not supported.\"}}
```

**Comment by jamesmhaley** [comment]
Any movement on this @lemonJS?

**Pull request closed without merging**
